package org.piyush.model.dynamodb;

import org.piyush.constant.Priority;
import org.piyush.constant.TaskStatus;
import org.piyush.converters.ListSubTaskConverter;
import org.piyush.model.taskmanagement.SubTask;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@DynamoDbBean
public class DbTask {
  public static final TableSchema<DbTask> TABLE_SCHEMA = TableSchema.fromBean(DbTask.class);

  private String id;
  private String title;
  private String description;
  private Priority priority;
  private Instant deadline;
  private List<String> labels = new ArrayList<>();
  private List<SubTask> subTasks = new ArrayList<>();
  private String assignee;
  private TaskStatus status;
  private String parentTaskId;
  private List<String> dependentTaskIds = new ArrayList<>();
  private Instant createdAt;
  private Instant updatedAt;
  private Long version;

  @DynamoDbPartitionKey
  @DynamoDbAutoGeneratedUuid
  public String getId() {
    return id;
  }

  @DynamoDbAttribute("title")
  public String getTitle() {
    return title;
  }

  @DynamoDbAttribute("description")
  public String getDescription() {
    return description;
  }

  @DynamoDbAttribute("priority")
  public Priority getPriority() {
    return priority;
  }

  @DynamoDbSortKey
  @DynamoDbAttribute("deadline")
  @DynamoDbSecondaryPartitionKey(indexNames = {"DeadlineIndex"})
  public Instant getDeadline() {
    return deadline;
  }

  @DynamoDbAttribute("labels")
  public List<String> getLabels() {
    return labels;
  }

  @DynamoDbAttribute("subTasks")
  @DynamoDbConvertedBy(ListSubTaskConverter.class)
  public List<SubTask> getSubTasks() {
    return subTasks;
  }

  @DynamoDbAttribute("assignee")
  @DynamoDbSecondaryPartitionKey(indexNames = {"AssigneeIndex"})
  public String getAssignee() {
    return assignee;
  }

  @DynamoDbAttribute("status")
  @DynamoDbSecondaryPartitionKey(indexNames = {"StatusIndex"})
  public TaskStatus getStatus() {
    return status;
  }

  @DynamoDbAttribute("parentTaskId")
  public String getParentTaskId() {
    return parentTaskId;
  }

  @DynamoDbAttribute("dependentTaskIds")
  public List<String> getDependentTaskIds() {
    return dependentTaskIds;
  }

  @DynamoDbAttribute("createdAt")
  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getCreatedAt() {
    return createdAt;
  }

  @DynamoDbAttribute("updatedAt")
  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getUpdatedAt() {
    return updatedAt;
  }

  @DynamoDbVersionAttribute
  public Long getVersion() {
    return version;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setPriority(Priority priority) {
    this.priority = priority;
  }

  public void setDeadline(Instant deadline) {
    this.deadline = deadline;
  }

  public void setLabels(List<String> labels) {
    this.labels = labels;
  }

  public void setSubTasks(List<SubTask> subTasks) {
    this.subTasks = subTasks;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public void setStatus(TaskStatus status) {
    this.status = status;
  }

  public void setParentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
  }

  public void setDependentTaskIds(List<String> dependentTaskIds) {
    this.dependentTaskIds = dependentTaskIds;
  }

  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  public void setUpdatedAt(Instant updatedAt) {
    this.updatedAt = updatedAt;
  }

  public void setVersion(Long version) {
    this.version = version;
  }
}